name: "dbt_takehome_project"
version: "1.0"
config-version: 2

profile: "dbt_takehome_project"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_takehome_project:
    staging:
      materialized: view
    core:
      materialized: table

seeds:
  dbt_takehome_project:
    +schema: utils
    enabled: true
    quoting:
      header: true
      column: true

snapshots:
  dbt_takehome_project:
    +target_schema: snapshots
