version: 2

models:
  - name: stg_contacts
    description: "Staging model for contacts"
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null

  - name: stg_orders
    description: "Staging model for orders"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - not_null
